---
- hosts: all
  tasks:

    - name: Setear Hostname
      hostname: name={{ ansible_hostname }}

    - name: Instalar repositorio epel
      yum:
        name:
          - epel-release


    - name: Instalar paquetes comunes
      yum:
        name:
          - git
          - vim
          - mlocate
          - wget



    - name: Configurar zona horaria
      timezone:
        name: America/Montevideo


  become: true
  become_user: root
